using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;
using ArjuyScaffold.Models;
using ModelContextProtocol.Server;

namespace ArjuyScaffold.Tools;

/// <summary>
/// Generates Persistence.Database-layer EF Core configuration classes following the real arjuy*
/// convention found in ArjuyTurismo.Persistence.Database: one IEntityTypeConfiguration&lt;T&gt;
/// class per entity, at Persistence.Database/Configurations/{Module}/{Entity}Configuration.cs,
/// with ToTable, HasKey, HasQueryFilter(soft delete) unless the entity is a lookup table, per-
/// property Fluent API calls, and relationship wiring (HasMany/HasOne + WithOne/WithMany +
/// HasForeignKey + OnDelete). Registration (ApplyConfigurationsFromAssembly on the target
/// DbContext) is automatic in every arjuy* project and therefore NOT generated here.
/// </summary>
[McpServerToolType]
public static class EfConfigurationTool
{
    [McpServerTool(Name = "generate_ef_configuration")]
    [Description(
        "Generates the C# source for an EF Core IEntityTypeConfiguration<{Entity}> class " +
        "following the arjuy* convention (Persistence.Database/Configurations/{Module}/" +
        "{Entity}Configuration.cs): ToTable, HasKey(x => x.Id), HasQueryFilter(x => !x.Deleted) " +
        "for soft delete (OMITTED when 'isLookup' is true, since lookup/catalog tables are not " +
        "soft-deletable in the real convention), one builder.Property(...) call per property " +
        "(IsRequired/HasMaxLength as configured), and optional relationships " +
        "(HasMany/HasOne + WithOne/WithMany + HasForeignKey + OnDelete(DeleteBehavior.X)). No " +
        "expression-bodied members — explicit block body with 'return' semantics via Configure(...). " +
        "Registration via ApplyConfigurationsFromAssembly on the target DbContext is automatic in " +
        "every arjuy* project and is NOT generated by this tool. Returns the generated C# source " +
        "as a string; this tool does not write files to disk.")]
    public static string GenerateEfConfiguration(
        [Description("Entity name in PascalCase, e.g. 'Category'. Generates CategoryConfiguration.")] string entityName,
        [Description("Scalar properties to configure via the Fluent API (name + IsRequired + optional MaxLength). The properties themselves are assumed to already exist on the entity (generated separately by generate_entity) — this tool only emits builder.Property(...) constraints.")] List<EfPropertyDefinition> properties,
        [Description("Optional relationships to configure (HasMany/HasOne + WithOne/WithMany + optional HasForeignKey + OnDelete). Omit or pass an empty list for an entity with no navigation properties to configure.")] List<EfRelationDefinition>? relations = null,
        [Description("When true, OMITS builder.HasQueryFilter(x => !x.Deleted) — use for lookup/catalog entities that are not soft-deletable. Defaults to false.")] bool isLookup = false,
        [Description("Table name passed to builder.ToTable(...). Defaults to '{EntityName}s' (naive pluralization by appending 's') if omitted.")] string? tableName = null,
        [Description("Namespace for the generated configuration class. Defaults to a generated namespace if omitted.")] string? namespaceName = null,
        [Description("Namespace where the entity class lives, used for the using directive. Defaults to a generated namespace if omitted.")] string? entityNamespace = null)
    {
        if (string.IsNullOrWhiteSpace(entityName))
        {
            throw new ArgumentException("entityName is required.", nameof(entityName));
        }

        string resolvedTableName = string.IsNullOrWhiteSpace(tableName) ? entityName + "s" : tableName;
        string resolvedNamespace = namespaceName ?? "ArjuyScaffold.Generated.Persistence.Database.Configurations";
        string resolvedEntityNamespace = entityNamespace ?? "ArjuyScaffold.Generated.Domain.Entities";
        List<EfPropertyDefinition> resolvedProperties = properties ?? new List<EfPropertyDefinition>();
        List<EfRelationDefinition> resolvedRelations = relations ?? new List<EfRelationDefinition>();

        string className = entityName + "Configuration";

        StringBuilder sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("using Microsoft.EntityFrameworkCore;");
        sourceBuilder.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
        sourceBuilder.AppendLine("using " + resolvedEntityNamespace + ";");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("namespace " + resolvedNamespace + ";");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("public class " + className + " : IEntityTypeConfiguration<" + entityName + ">");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    public void Configure(EntityTypeBuilder<" + entityName + "> builder)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        builder.ToTable(\"" + resolvedTableName + "\");");
        sourceBuilder.AppendLine("        builder.HasKey(x => x.Id);");

        if (!isLookup)
        {
            sourceBuilder.AppendLine("        builder.HasQueryFilter(x => !x.Deleted);");
        }

        if (resolvedProperties.Count > 0)
        {
            sourceBuilder.AppendLine();

            foreach (EfPropertyDefinition property in resolvedProperties)
            {
                AppendPropertyConfiguration(sourceBuilder, property);
            }
        }

        if (resolvedRelations.Count > 0)
        {
            sourceBuilder.AppendLine();

            foreach (EfRelationDefinition relation in resolvedRelations)
            {
                AppendRelationConfiguration(sourceBuilder, relation);
            }
        }

        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static void AppendPropertyConfiguration(StringBuilder sourceBuilder, EfPropertyDefinition property)
    {
        string propertyName = string.IsNullOrWhiteSpace(property.Name) ? "PropertyName" : property.Name;

        StringBuilder lineBuilder = new StringBuilder();
        lineBuilder.Append("        builder.Property(x => x.").Append(propertyName).Append(')');

        if (property.IsRequired)
        {
            lineBuilder.Append(".IsRequired()");
        }

        if (property.MaxLength.HasValue)
        {
            lineBuilder.Append(".HasMaxLength(").Append(property.MaxLength.Value).Append(')');
        }

        lineBuilder.Append(';');

        sourceBuilder.AppendLine(lineBuilder.ToString());
    }

    private static void AppendRelationConfiguration(StringBuilder sourceBuilder, EfRelationDefinition relation)
    {
        bool isHasMany = string.Equals(relation.RelationType, "HasMany", StringComparison.OrdinalIgnoreCase);
        string navigationMethod = isHasMany ? "HasMany" : "HasOne";
        string inverseMethod = isHasMany ? "WithOne" : "WithMany";
        string inverseArgument = string.IsNullOrWhiteSpace(relation.InverseNavigationProperty)
            ? string.Empty
            : "x => x." + relation.InverseNavigationProperty;
        string resolvedDeleteBehavior = string.IsNullOrWhiteSpace(relation.DeleteBehavior) ? "Restrict" : relation.DeleteBehavior;

        sourceBuilder.AppendLine("        builder." + navigationMethod + "(x => x." + relation.PropertyName + ")");
        sourceBuilder.AppendLine("            ." + inverseMethod + "(" + inverseArgument + ")");

        if (!string.IsNullOrWhiteSpace(relation.ForeignKeyProperty))
        {
            sourceBuilder.AppendLine("            .HasForeignKey(x => x." + relation.ForeignKeyProperty + ")");
        }

        sourceBuilder.AppendLine("            .OnDelete(DeleteBehavior." + resolvedDeleteBehavior + ");");
    }
}
