using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Text;
using ArjuyScaffold.Models;
using ModelContextProtocol.Server;

namespace ArjuyScaffold.Tools;

/// <summary>
/// Generates Domain-layer entity classes following the arjuy* Clean Architecture
/// convention: entities inherit the abstract base class Entity, already present in
/// every arjuy* project at Domain/Common/Entity.cs, which carries Id, CreatedAt,
/// UpdatedAt and the soft-delete flag Deleted. This tool does NOT (re)generate that
/// base class — it is assumed to already exist in the target project — it only
/// generates the DERIVED entity with its own specific properties.
/// </summary>
[McpServerToolType]
public static class EntityTool
{
    [McpServerTool(Name = "generate_entity")]
    [Description(
        "Generates a C# Domain entity class that inherits Entity (Id: int, " +
        "CreatedAt: DateTime = ArgentinaTime.Now, UpdatedAt: DateTime?, Deleted: bool), following the " +
        "arjuy* Clean Architecture convention. Entity already exists in the target project at " +
        "Domain/Common/Entity.cs and is NOT generated by this tool — do not add Id, CreatedAt, " +
        "UpdatedAt or Deleted to the properties list, they are inherited. Properties are " +
        "auto-implemented (property syntax is not an expression-bodied member, so it is allowed). " +
        "Returns the generated C# source as a string. If 'outputFilePath' is provided, the file is " +
        "ALSO written to disk at that path (opt-in, disabled by default) — pass an absolute path " +
        "inside your Domain project, e.g. 'C:\\repo\\MyApp.Domain\\Entities\\Ticket.cs'.")]
    public static string GenerateEntity(
        [Description("Entity name in PascalCase, e.g. 'Ticket'.")] string entityName,
        [Description("Properties to add to the entity (name + C# type each). Do NOT include Id, CreatedAt, UpdatedAt or Deleted — those are inherited from Entity.")] List<PropertyDefinition> properties,
        [Description("Namespace for the generated class. Defaults to '{EntityName}.Domain.Entities' style if omitted.")] string? namespaceName = null,
        [Description("Name of the base class entities inherit from. Defaults to 'Entity', the arjuy* Clean Architecture convention (Domain/Common/Entity.cs). Override only if the target project genuinely uses a different name.")] string? baseEntityName = null,
        [Description("Optional absolute path to also write the generated .cs file to disk. When omitted, no file is written and only the string is returned.")] string? outputFilePath = null)
    {
        if (string.IsNullOrWhiteSpace(entityName))
        {
            throw new ArgumentException("entityName is required.", nameof(entityName));
        }

        string resolvedNamespace = namespaceName ?? "ArjuyScaffold.Generated.Domain.Entities";
        string resolvedBaseEntity = string.IsNullOrWhiteSpace(baseEntityName) ? "Entity" : baseEntityName;

        StringBuilder sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("namespace " + resolvedNamespace + ";");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("public class " + entityName + " : " + resolvedBaseEntity);
        sourceBuilder.AppendLine("{");

        if (properties != null)
        {
            foreach (PropertyDefinition property in properties)
            {
                string propertyType = string.IsNullOrWhiteSpace(property.Type) ? "string" : property.Type;
                string propertyName = string.IsNullOrWhiteSpace(property.Name) ? "PropertyName" : property.Name;
                sourceBuilder.AppendLine("    public " + propertyType + " " + propertyName + " { get; set; }");
            }
        }

        sourceBuilder.AppendLine("}");

        string generatedSource = sourceBuilder.ToString();

        if (!string.IsNullOrWhiteSpace(outputFilePath))
        {
            string? directory = Path.GetDirectoryName(outputFilePath);
            if (!string.IsNullOrWhiteSpace(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(outputFilePath, generatedSource);
        }

        return generatedSource;
    }
}
